apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
    configuration:
      auto.create.topics.enable: false
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 2Gi
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 2Gi
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 2Gi
    userOperator:
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 2Gi
